name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:

jobs:
  java_build:
    if: github.repository == 'langchain4j/langchain4j-community'
    strategy:
      matrix:
        java_version:
          - 17
        include:
          - java_version: '17'
            mvn_opts: '-Dtinylog.writer.level=info'
      max-parallel: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with JDK ${{ matrix.java_version }}
        run: |
          ## compile and verify javadocs on ALL modules
          mvn -B -U -T8C test javadoc:aggregate \
            --fail-at-end \
            ${{ matrix.mvn_opts }}
          
          ## run tests for some modules
          mvn -B -U verify \
              --fail-at-end \
              -DskipXinferenceITs \
              -Dmaven.test.failure.ignore=true \
              ${{ matrix.mvn_opts }}

      - name: Upload Test Reports
        if: always() # always run even if the previous step failed or was cancelled
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports-${{ matrix.java-version }}
          path: '**/target/*-reports/*'

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step failed or was cancelled
        with:
          report_paths: '**/target/*-reports/TEST-*.xml'
          annotate_only: true
